POST http://localhost:5001/api/auth/register
Content-Type: application/json

{
    "username": "khoata0605",
    "password": "12345"
}

###
POST http://localhost:5001/api/auth/login
Content-Type: application/json

{
    "username": "admin",
    "password": "root"
}

###
POST http://localhost:5001/api/posts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MmU3NTk0ZDc1YzY4MDMzN2VmNTIwNTkiLCJpYXQiOjE2NTk1Nzc4NTN9.JVn8OHqviHtaqFyAobw5NOXgZczu0ccTB1GQdONcD2s

{
    "title": "ReactJS",
    "description": "Learn ReactJS on the web",
    "url": "fullstack.edu.vn",
    "status": "TO LEARN"
}

###
GET http://localhost:5001/api/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MmU3NTk0ZDc1YzY4MDMzN2VmNTIwNTkiLCJpYXQiOjE2NTk1Nzc4NTN9.JVn8OHqviHtaqFyAobw5NOXgZczu0ccTB1GQdONcD2s

###
PUT http://localhost:5001/api/posts/62e790a146131ff0a3461743
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MmU3NTk0ZDc1YzY4MDMzN2VmNTIwNTkiLCJpYXQiOjE2NTkzNDY5NDF9.Y7UTuEnDth-C9-V4OnWdoFOHk-EOxh8y9Ejp5K2TAqo

{
    "title": "VueJS",
    "description": "Vueeeee",
    "url": "https://vuejs.org",
    "status": "LEARNING"
}

###
DELETE http://localhost:5001/api/posts/62e77df0d62884dba3e03a3c
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MmU3NTk0ZDc1YzY4MDMzN2VmNTIwNTkiLCJpYXQiOjE2NTkzNDY5NDF9.Y7UTuEnDth-C9-V4OnWdoFOHk-EOxh8y9Ejp5K2TAqo
